name: intl_country_data
description: Dart package containing country data including international dialing codes and telephone number lengths. Other data include ISO 3166 2 letter country codes, flag emojis and country name translations. This package can be used in Dart or Flutter environments.
version: 1.2.5
repository: https://github.com/jimmyff/intl_country_data

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
